In [1]:
import numpy as np
import random
from model import Model  # Assume the refactored code is saved in model.py
from rbm import RBM
from rbm_operator import *
from test_rbm_operator import *

In [7]:
import numpy as np

# Given matrix S
S = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Extract the diagonal elements of S
diagonal_elements = np.diagonal(S)

# Create a diagonal matrix S' with the same diagonal elements as S
S_prime = np.diag(diagonal_elements)

print("Original matrix S:")
print(S)
print("\nMatrix S' with same diagonal elements but zero elsewhere:")
print(S_prime)


Original matrix S:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix S' with same diagonal elements but zero elsewhere:
[[1 0 0]
 [0 5 0]
 [0 0 9]]
